apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zookeeper

helmCharts:
- name: zookeeper
  releaseName: zookeeper-team1
  namespace: zookeeper
  repo: https://charts.bitnami.com/bitnami
  valuesFile: values.yaml
